// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDviqVR0gxplnU76_VJ5PvV5sfE5BvpcNw',
    appId: '1:312243560479:web:3c47eeaabcd75640ba752a',
    messagingSenderId: '312243560479',
    projectId: 'noteflow-auth-project',
    authDomain: 'noteflow-auth-project.firebaseapp.com',
    storageBucket: 'noteflow-auth-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2SDFKYGeajrRxuJSnY9IiSHLLTpldRM',
    appId: '1:312243560479:android:2096c728dccf0bedba752a',
    messagingSenderId: '312243560479',
    projectId: 'noteflow-auth-project',
    storageBucket: 'noteflow-auth-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEUMmHgo3YYG-PZL7riEH_uo9VdvhaPFA',
    appId: '1:312243560479:ios:854297c2a90f40f0ba752a',
    messagingSenderId: '312243560479',
    projectId: 'noteflow-auth-project',
    storageBucket: 'noteflow-auth-project.firebasestorage.app',
    iosBundleId: 'com.example.noteflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEUMmHgo3YYG-PZL7riEH_uo9VdvhaPFA',
    appId: '1:312243560479:ios:854297c2a90f40f0ba752a',
    messagingSenderId: '312243560479',
    projectId: 'noteflow-auth-project',
    storageBucket: 'noteflow-auth-project.firebasestorage.app',
    iosBundleId: 'com.example.noteflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDviqVR0gxplnU76_VJ5PvV5sfE5BvpcNw',
    appId: '1:312243560479:web:c1083727b34725a5ba752a',
    messagingSenderId: '312243560479',
    projectId: 'noteflow-auth-project',
    authDomain: 'noteflow-auth-project.firebaseapp.com',
    storageBucket: 'noteflow-auth-project.firebasestorage.app',
  );
}
